In [ ]:
import numpy as np

## Instructions
1. Do not import any other library. 
2. This assignment primarily focuses on getting a hands on practise for numpy library.
3. Examples are given for most of the questions. You are free to take different values inside the arrays as long as the requirements are questions are met.
4. We have referenced the 1D array as sample_1 and 2D array as sample_2 in the notebook. You are free to change the variable's name.
5. Go through these resources in order ro learn and practise numpy operations : <a href="https://www.w3schools.com/python/numpy/numpy_intro.asp">Resource 1 </a> , <a href="https://realpython.com/numpy-tutorial/">Resource 2 </a>
6. You can also read the documentation of all numpy functions from this <a href="https://numpy.org/doc/stable/user/absolute_beginners.html">Link </a>

#### <b> <font color='red'> Que 1.1 - Defining a numpy matrix </b>   -> Define a 1D numpy array having 6 elements. Print the dimensions, rows and columns of the array </font>

<br> <b>  Example </b> </br>
sample_1 = [ 5, 6, 2, 7, 8, 8]
  - Array dimension = 1
  - Number of rows = 1
  - Number of columns = 6



In [3]:
#define the 1d array
#WRITE CODE BELOW
sample_1 = np.array([5,6,2,7,8,8])



In [4]:
#printing the 1D array that you have defined above
print(sample_1)
# print the dimension, rows and columns of the array
#WRITE CODE BELOW
print(np.size(sample_1))
print(np.shape(sample_1))



[5 6 2 7 8 8]
6
(6,)


#### <b> <font color='red'> Que 1.2 - Defining a numpy matrix </b>   -> Define a 2D numpy array having 4 rows and 3 columns. Print the dimensions, rows and columns of the array </font>

<br> <b>  Example </b> </br>
$$\begin{bmatrix} 6 & 2 & 1  \\ 3 & 0 & 1 \\ 0 & 2 & 4  \\ 5 & 6 & 8 \end{bmatrix}$$

  - Array dimension = 2
  - Number of rows = 4
  - Number of columns = 3





In [5]:
#define the 2d array
#WRITE CODE BELOW
sample_2 = np.array([[6,2,1],[3,0,1],[0,2,4],[5,6,8]])



In [6]:
#printing the 2D array that you have defined above
print(sample_2)
# print the dimension, rows and columns of the array
#WRITE CODE BELOW
print(np.size(sample_2))
print(np.shape(sample_2))




[[6 2 1]
 [3 0 1]
 [0 2 4]
 [5 6 8]]
12
(4, 3)


#### <b> <font color='red'> Que 2.1 - Accessing elements </b>   -> Print the first element of 1D array and 2D array that you have defined in the previous question </font>

<br> <b>  Example - Accessing first element of sample_1 and sample_2 defined in prev que</b> </br>
- first_sample1 = 2
- first_sample2 = 6

Note - You can get different output if you have defined different elements in your arrays.



In [7]:
#access first element from both 1D array and 2D array
#WRITE CODE BELOW
#first element of 1D array 
first_sample1 = sample_1[0]

#first element of 2D array
first_sample2 = sample_2[0,0]

print(first_sample1,first_sample2)


5 6


#### <b> <font color='red'> Que 2.2 - Array Slicing </b>  </font>  
<font color='red'> 
1. Print first three elements of sample_1 (1D array)
2. Print all elements from second column from sample_2  (2D array) 
3. Print all elements which which belongs to (3rd and 4th row) and (2nd and 3rd column) from sample_2 (2d Array)

<br> <b>  Example - Output for sample_1 and sample_2 array that were defined in the first que</b> </br>
<br> first_three_sample1 = [5, 6 ,2] </br>
<br> second_col_sample2 = [ 2, 0 , 2 , 6] </br>
<br> result_sample2 = 
$$\begin{bmatrix} 2 & 4  \\ 6 & 8  \end{bmatrix}$$



In [8]:
#define three variables
#first three variables of sample_1 (1D array)
first_three_sample1 =(sample_1[:3])
print(first_three_sample1)
#print all elements from second column from sample_2 (2D array)
second_col_sample2 = sample_2[:,1]
print(second_col_sample2)

#print all elements from 3rd and 4th row and 2nd and 3rd column from sample_2 (2D array)
result_sample2 = sample_2[2:4,1:3]
print(result_sample2)

[5 6 2]
[2 0 2 6]
[[2 4]
 [6 8]]


#### <b> <font color='red'> Que 3 - Sorting the array - Sort the 1D array (sample_1)  and print it</b>  </font>  

<br> <b>  Example - Output for sample_1  array that was defined in the first que</b> </br>
sorted_sample_1 = [ 2, 5, 6, 7, 8, 8 ]

In [9]:
#sort the 1D array (sample_1)
#WRITE code below
sorted_sample_1 = sorted(sample_1)
print(sample_1)
print(sorted_sample_1)




[5 6 2 7 8 8]
[2, 5, 6, 7, 8, 8]


#### <b> <font color='red'> Que 4 - Finding the mean and maximum value of rows and columns </font>  </b>

<font color='red'> 
1. Find the mean of sample_1 (1D array). </font>
<font color='red'> 
2. Find the maximum value from each column of sample_2 (2D array). </font>


<br> <b>  Example - Output for sample_1 and sample_2 array that were defined in the first que </b> </br>
<br>mean_sample_1 =      6.0 </br>
<br>max_column_sample2 = [6, 6 , 8] </br>

In [10]:
#mean of  one_d array
#Write code below
mean_sample1 = np.mean(sample_1)
print(mean_sample1)


#max value from each column
#write code below
max_column_sample2 = np.max(sample_2,axis=0)
print("\n",sample_2)
print(max_column_sample2)



6.0

 [[6 2 1]
 [3 0 1]
 [0 2 4]
 [5 6 8]]
[6 6 8]


#### <b> <font color='red'>Que 5 - Defining a random numpy array with given shape </font></b>
<font color='red'> Take two inputs from the user <b>num_rows</b> and <b> num_cols</b>, you have to define a random numpy matrix with dimensions (num_rows x num_cols) 
Hint - You can use numpy.random function </font>

In [20]:
print('Enter the number of rows')
num_rows= int(input())
print('Enter the number of columns')
num_cols = int(input())

Enter the number of rows


In [1]:
# define a random matrix of size (num_rows x num_cols)
#WRITE Code below
random_matrix=np.random.rand(num_rows,num_cols)
print("randome matrix: ",(num_rows,num_cols),":")
print(random_matrix)



NameError: name 'np' is not defined

#### <b> <font color='red'>Que 6.1 - Elementwise Multiplication and Matrix multiplication  </font></b>
<font color='red'> There are two ways of multiplication of numpy arrays. The first one is element wise multiplication, where you have to multiply both arrays elementwise.  </font>
<font color='red'> Define two 1D matrices having 4 elements each, and multiply them elementwise. </font>

<br> <b>  Example </b> </br>

<br> array_1 = [2 , 3, 4 , 5] </br>
<br> array_2 = [3,  4,  5,  6] </br>
<br> result_array = [6, 12 , 20, 30 ] </br>




In [3]:
array_1 = np.array([2,3,4,5])
array_2 = np.array([3, 4, 5, 6])

#multiply these two arrays
#store the result in result_array

result_array = array_1*array_2
print(result_array)

[ 6 12 20 30]


#### <b> <font color='red'>Que 6.2 - Elementwise Multiplication and Matrix multiplication  </font></b>
<font color='red'> The second one is matrix multiplication, where you have to multiply both arrays according to standard matrix multiplication.  </font>
<font color='red'> Define two 2D matrices first_one of size 2X5 and second_one of size 5X2. Perform matrix mutiplication and print shape of resultant array. </font>

<br> <b>  Example </b> </br>
<br> If you perform matrix multiplication of array_1 and array_2  </br>
array_1  = $$\begin{bmatrix} 1 & 3 &4 &5 &6  \\ 2 &5 &7 &8&9  \end{bmatrix}$$
array_2  = $$\begin{bmatrix} 2 & 4  \\ 2 & 6 \\0 &3 \\8 & 0 \\ 1&4   \end{bmatrix}$$

 will get the resultant array as 
$$\begin{bmatrix} 54 & 58  \\ 87 & 95  \end{bmatrix}$$

In [9]:
array_1 = np.array([[1,3,4,5,6],[2,5,7,8,9]])
array_2 = np.array([[2,4],[2,6],[0,3],[8,0],[1,4]])

#multiply these two arrays using matrix multiplication
#store the result in result_array

result_array =array_1 @ array_2
print(result_array)
print(result_array.shape)

[[54 58]
 [87 95]]
(2, 2)


#### <b> <font color='red'>Que 7 - Creating a copy of array</font></b>
<font color='red'> Define a matrix named original_array with some values. Create a copy of this array named copy_array. Now change the first element of the copy_array and then print original_array and copy_array.
<br> Note - While printing you have to make sure that only the copy_array is changed and not the original_array.</br></font>

<b> Example </b>
- original_array = [2 , 4 ,6 , 8]
- copy_array = [ 2, 4, 6 ,8 ]
<br> Modify the first element of copy array to 10 and then print both arrays </br>
- original_array = [2 ,4, 6, 8]
- copy_array = [10, 4, 6, 8]



In [11]:
#define your original_array and copy array 
#WRITE CODE BELOW
original_array = np.array([2,4,6,8])

copy_array = original_array.copy()

#modify the first element of copy_array
copy_array[0]=10

#print both original and copy_array
print(f"original_array: {original_array}, copy_array:{copy_array}")


original_array: [2 4 6 8], copy_array:[10  4  6  8]


#### <b> <font color='red'> Que 8 - Concatenating the arrays along different axes</b> </font>
<font color='red'> Given two matrices array_1 and array_2 as follows </font>

array_1 = $$\begin{bmatrix} 10 & 20  \\ 30 & 40  \end{bmatrix}$$
array_2 = $$\begin{bmatrix} 50 & 60  \\ 70 & 80  \end{bmatrix}$$

<font color='red'> You have to concatenate array_1 and array_2 row-wise and column wise such that the result matrices are as follows.

row_concat_array = $$\begin{bmatrix} 10 & 20  \\ 30 & 40 \\ 50 & 60  \\ 70 & 80  \end{bmatrix}$$
col_concat_array = $$\begin{bmatrix} 10 & 20 & 50 & 60  \\ 30 & 40  & 70 &80 \end{bmatrix}$$


In [16]:
#Defining array_1 and array_2
array_1 = np.array([[10,20],[30,40]])
array_2=np.array([[50,60],[70,80]])

#concatenate both the arrays row wise and column wise
#WRITE CODE BELOW
# Concatenating row-wise (axis=0)
row_wise_concat = np.concatenate((array_1, array_2), axis=0)

# Concatenating column-wise (axis=1)
column_wise_concat = np.concatenate((array_1, array_2), axis=1)

print("Row-wise Concatenation:")
print(row_wise_concat)

print("\nColumn-wise Concatenation:")
print(column_wise_concat)

Row-wise Concatenation:
[[10 20]
 [30 40]
 [50 60]
 [70 80]]

Column-wise Concatenation:
[[10 20 50 60]
 [30 40 70 80]]


#### <b> <font color='red'> Que 8 Broadcasting the arrays </b>
If the dimensions of two arrays are dissimilar, element-to-element operations are not possible. However, operations on arrays of non-similar shapes is still possible in NumPy, because of the broadcasting capability. The smaller array is broadcast to the size of the larger array so that they have compatible shapes </font>

<font color='red'> Que 8.1 - Consider an array my_array of size 1 x 5 . Increment each element of the array by 1 and store it in  result _array</font>

<b> Example </b>
<br> my_array = [ 5 , 12, 7 ,3] </br>
<br> result_array = [ 6, 13 , 8, 4]. </br>


In [15]:
#define my_array
my_array = np.array([5, 12 ,7 ,3])

#Increment each element of my_array by 1
#WRITE CODE BELOW
ans=my_array+np.array([1,1,1,1])
print(ans)



[ 6 13  8  4]


<font color='red'> Que 2 - Consider an array of size of size 3x3 . You have to increment each element of column 1 by 5, column 2 by 10 and column 3 by 15. </font> </br>
my_array = $$\begin{bmatrix} 5 & 0 & 3  \\ 3 & 4 & 6 \\ 8& 0 & 7 \end{bmatrix}$$

result_array = $$\begin{bmatrix} 10 & 10 & 18  \\ 8 & 14 & 21 \\ 13 & 10 & 22 \end{bmatrix}$$

In [12]:
#define my_array
my_array = np.array([[5, 0 ,3],[3,4,6],[8,0,7]])

#Increment column_1 by 5, column_2 by 10 and column_3 by 15
#WRITE CODE BELOW
result_array = my_array+np.array([5,10,15])
print(result_array)





[[10 10 18]
 [ 8 14 21]
 [13 10 22]]


In [ ]:
#PANDAS ASSIGNMENT
import pandas as pd
import numpy as np

file_path = "bank_transactions-2-2.csv"
df = pd.read_csv(file_path)

# Display basic information about the dataset
print("Basic Information:")
print(df.info())
print("\nFirst 5 rows:")
print(df.head())

# Provide basic statistics
print("\nStatistics:")
print(df.describe())

# Calculate total and average transaction amount per customer
customer_stats = df.groupby("CustomerID")["TransactionAmount (INR)"].agg([np.sum, np.mean])
customer_stats.rename(columns={'sum': 'TotalAmount', 'mean': 'AverageAmount'}, inplace=True)

print("\nTotal and Average Transaction Amount per Customer:")
print(customer_stats.head())

# Identify customers with the highest total transaction amount
top_customers = customer_stats.sort_values(by="TotalAmount", ascending=False).head(10)

print("\nTop 10 Customers by Total Transaction Amount:")
print(top_customers)

Basic Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048567 entries, 0 to 1048566
Data columns (total 3 columns):
 #   Column                   Non-Null Count    Dtype  
---  ------                   --------------    -----  
 0   CustomerID               1048567 non-null  object 
 1   TransactionDate          1048567 non-null  object 
 2   TransactionAmount (INR)  1048567 non-null  float64
dtypes: float64(1), object(2)
memory usage: 24.0+ MB
None

First 5 rows:
  CustomerID TransactionDate  TransactionAmount (INR)
0   C5841053          2/8/16                     25.0
1   C2142763          2/8/16                  27999.0
2   C4417068          2/8/16                    459.0
3   C5342380          2/8/16                   2060.0
4   C9031234          2/8/16                   1762.5

Statistics:
       TransactionAmount (INR)
count             1.048567e+06
mean              1.574335e+03
std               6.574743e+03
min               0.000000e+00
25%               1.6100

C:\Users\Kartik\AppData\Local\Temp\ipykernel_23544\1784851946.py:18: FutureWarning: The provided callable <function sum at 0x0000029858841760> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  customer_stats = df.groupby("CustomerID")["TransactionAmount (INR)"].agg([np.sum, np.mean])
C:\Users\Kartik\AppData\Local\Temp\ipykernel_23544\1784851946.py:18: FutureWarning: The provided callable <function mean at 0x0000029858842840> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  customer_stats = df.groupby("CustomerID")["TransactionAmount (INR)"].agg([np.sum, np.mean])



Total and Average Transaction Amount per Customer:
            TotalAmount  AverageAmount
CustomerID                            
C1010011         5106.0         2553.0
C1010012         1499.0         1499.0
C1010014         1455.0          727.5
C1010018           30.0           30.0
C1010024         5000.0         5000.0

Top 10 Customers by Total Transaction Amount:
            TotalAmount  AverageAmount
CustomerID                            
C7319271     1560034.99     1560034.99
C6677159     1380002.88     1380002.88
C4141768      991132.22      991132.22
C8217728      724472.00      362236.00
C1830891      720001.16      720001.16
C6549785      600008.32      600008.32
C5036642      600003.45      600003.45
C4328064      569500.27      569500.27
C1425138      561001.00      561001.00
C5833636      557000.73      557000.73


#<b> END OF ASSIGNMENT <b>